name: Codeception

on:
  push:

jobs:
  build:
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_USER: phalcon
          MYSQL_DATABASE: phalcon
          MYSQL_PASSWORD: secret
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: phalcon
          POSTGRES_DB: phalcon
      redis:
        image: redis:5-alpine
        ports:
          - 6379
    runs-on: ubuntu-latest
    name: Run basic test on latest Phalcon
    steps:
      - name: Git checkout
        uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          tools: pecl
          extensions: mbstring, intl, json, phalcon, imagick, apcu_bc
      - name: Install packages
        run: composer install
      - name: Run tests
        env:
          DATA_MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
          DATA_POSTGRES_PORT: ${{ job.services.postgres.ports['5432'] }}
          DATA_REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
        run: |
          cp tests/_ci/.env.default .env
          vendor/bin/codecept run --ext DotReporter
