name: Codeception

on:
  push:

jobs:
  build:
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_USER: phalcon
          MYSQL_DATABASE: phalcon
          MYSQL_PASSWORD: secret
      postgres:
        image: postgres:12-alpine
        ports:
          - 5432
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: phalcon
          POSTGRES_DB: phalcon
      redis:
        image: redis:5-alpine
        ports:
          - 6379
      memcached:
        image: memcached:1.5-alpine
        ports:
          - 11211
    runs-on: ubuntu-latest
    name: Run basic test on latest Phalcon
    steps:
      - name: Git checkout
        uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1
      - uses: actions/cache@v1
        id: cache
        with:
          path: path/to/dependencies
          key: ${{ runner.os }}_${{ hashFiles('.github/codeception.yml')_${{ hashFiles('composer.json') }}
      - name: Setup PHP
        if: steps.cache-primes.outputs.cache-hit != 'true'
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          ini-values: apc.enable_cli=on, session.save_path=/tmp
          tools: pecl
          extensions: mbstring, intl, json, phalcon, imagick, apcu_bc
      - name: Install packages
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: composer install
      - name: Run tests
        env:
          DATA_MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
          DATA_POSTGRES_PORT: ${{ job.services.postgres.ports['5432'] }}
          DATA_REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
          DATA_MEMCACHED_PORT: ${{ job.services.memcached.ports['11211'] }}
        run: |
          cp tests/_ci/.env.default .env
          vendor/bin/codecept build
          vendor/bin/codecept run --ext DotReporter cli
          vendor/bin/codecept run --ext DotReporter unit
          vendor/bin/codecept run --ext DotReporter integration
